"""
A coloured triangle is created from a row of colours, each of which is red,
green or blue. Successive rows, each containing one fewer colour than the
last, are generated by considering the two touching colours in the previous row.
If these colours are identical, the same colour is used in the new row.
If they are different, the missing colour is used in the new row. This is continued
until the final row, with only a single colour, is generated.

https://www.codewars.com/kata/coloured-triangles/train/python
"""

colors = ['G', 'B', 'R']


def triangle(row):
    """Find ending triangle colour."""
    next_row = ""
    while len(row) > 1:
        for i in range(len(row) - 1):
            col_1, col_2 = row[i], row[i+1]
            if col_1 == col_2:
                next_row += col_1
            else:
                missing_color = [x for x in colors if x not in [col_1, col_2]]
                next_row += missing_color[0]
        row, next_row = next_row, ""
    return row
